version: '3.8'

services:
  nextjs-app:
    build: ./nextjs_questionnaire
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs_questionnaire:/app  # ファイルを直接マウント
    depends_on:
      - db

  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - '3307:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql